name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    # The following configurations are required for Go 1.11 w/ dep on GitHub Actions
    # https://github.com/actions/setup-go/issues/102
    env:
      GOPATH: ${{ github.workspace }}
      GOBIN: ${{ github.workspace }}/bin
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/dtan4/ghrls

    steps:
      - name: Checkout
        uses: actions/checkout@v2

        # The following configurations are required for Go 1.11 w/ dep on GitHub Actions
        # https://github.com/actions/setup-go/issues/102
        with:
          fetch-depth: 1
          path: ${{ env.GOPATH }}/src/github.com/dtan4/ghrls
      - name: Setup Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16
      - name: Install dependencies
        run: |
          curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
          GO111MODULE=off make deps
      - name: Run tests
        run: GO111MODULE=off make ci-test
      - name: Send test coverage to Codecov
        uses: codecov/codecov-action@v1
