name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.11
      - name: Install dependencies
        run: make deps
      - name: Run tests
        run: make ci-test
      - name: Send test coverage to Codecov
        uses: codecov/codecov-action@v1
