name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v3.2.0
        with:
          go-version: 1.16
      - name: Run tests
        run: make ci-test
      - name: Send test coverage to Codecov
        uses: codecov/codecov-action@v1
